branch-defaults:
  master:
    environment: oksocios-prod
    group_suffix: null
deploy:
  artifact: target/oksocios-api-1.0.0.jar
global:
  application_name: oksocios
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Java 8
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
